---
title: "Finance Stats Final Project code"
author: "Qing Deng, Jinjin Dou, Hong Zhu"
date: "December 14, 2015"
output: html_document
---

## choose 20 stocks and plot the price

```{r}
library(quantmod)
library(copula)   # for copula functions
library(fGarch)   # need for standardized t density
library(MASS)     # need for fitdistr and kde2d
library(fCopulae) # additional copula functions 
library(quantmod)
library(xts)
library(timeDate)
stocklist = c('AMZN',  'COH',  'EXPE',  'MCD'   ,'NKE'  ,'RL'  ,'CCE', 'PEP',  'AXP', 
              'AIG',  'BLK','COF','GS','JPM','MCO', 'WFC',  'FDX'  ,'MMM','AAPL','FB')

par(mfrow=c(4,5))
for (i in stocklist) {
    
    x = get(getSymbols(i, src = 'yahoo', from = '2014-12-04', adjust=TRUE))
    xr = dailyReturn(x, type = "log")
    plot(xr, main=i)
    #plot(x[,4],main=i)
    assign(i, xr)
    
}
```

```{r}

```
```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
You can also embed plots, for example:

```{r, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
